version: '3.4'

services:
  angular-fund:
    image: angular-fund
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
    working_dir: /workspace
    #command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    #command: tail -f /dev/null  #npm run dev
    command: sleep infinity 